### ISSUE TITLE
Sherlock is licensed for the Plus edition, but the Lite edition is installed

### ISSUE THREAD

**Issue by jcdarwin** [putyourlightson/craft-sherlock#41]
I'v been doing some package updates on my craft site, and I notice now that I'm getting the message `Sherlock is licensed for the Plus edition, but the Lite edition is installed` appearing in the control panel, and I certainly do have a license for the plus ediion.

Given that we only do package updates via the command line, how do I upgrade from the lite edition to the plus edition?

Normally, I'd do something like `composer require putyourlightson/craft-sherlock` but I don't think this will work to install a particular edition?

**Comment by bencroker** [comment]
Clicking the edition badge should take you to the plugin page where you can change editions, I believe. If that fails, maybe try removing the license number and re-adding it after checking it is the right one (for the Plus edition). If that still doesn’t work then please contact Craft support, as this is a licensing issue rather than a Sherlock issue.

**Comment by jcdarwin** [comment]
Thanks -- yes, I had to change the edition from lite to pro (as trial), then remove the current (valid) pro licence key, refresh the page, and then change the newly generated license key back to the original one.
That's a bit more of a dance than I was expecting.
